# Creación de Perceptron

In [31]:
# Dataset de compuertas lógicas
# AND

X = [[0,0], [0,1], [1,0], [1,1]]
y = [0,0,0,1]

# OR
X = [[0,0], [0,1], [1,0], [1,1]]
y = [0,1,1,1]

# NOT
X = [[0], [1]]
y = [1,0]

# Modelo de Perceptron Scikit Learn

In [32]:
from sklearn.linear_model import Perceptron

neurona_and = Perceptron(max_iter = 50)
neurona_and

Perceptron(max_iter=50)

# Entrenamiento del Perceptron

In [33]:
neurona_and.fit(X, y)

Perceptron(max_iter=50)

# Obtener Predicción

In [34]:
y_pred = neurona_and.predict(X)
y_pred

array([1, 0])

# Evaluación del Modelo

In [35]:
import sklearn.metrics as metric
import numpy as np

metrica_precision = metric.accuracy_score(y, y_pred, normalize = True)
print(f"Precisión = {metrica_precision}")
print(f"Bias = {neurona_and.intercept_} > Parámetros = {neurona_and.coef_}")

Precisión = 1.0
Bias = [1.] > Parámetros = [[-2.]]


# Nuevo Dataset

In [53]:
# XOR
X = [[0,0], [0,1], [1,0], [1,1]]
y = [0, 1, 1, 0]

In [44]:
neurona_xor = Perceptron(max_iter = 500)
neurona_xor

Perceptron(max_iter=500)

In [45]:
neurona_xor.fit(X, y)

Perceptron(max_iter=500)

In [46]:
y_pred = neurona_xor.predict(X)
y_pred

array([0, 0, 0, 0])

In [47]:
import sklearn.metrics as metric
import numpy as np

metrica_precision = metric.accuracy_score(y, y_pred, normalize = True)
print(f"Precisión = {metrica_precision}")
print(f"Bias = {neurona_xor.intercept_} > Parámetros = {neurona_xor.coef_}")

Precisión = 0.5
Bias = [0.] > Parámetros = [[0. 0.]]


# Implementación de Perceptron Multicapa

In [54]:
from sklearn.neural_network import MLPClassifier

red_xor = MLPClassifier(solver = 'lbfgs', hidden_layer_sizes = (2,2,1), activation = 'logistic', max_iter = 50)

In [55]:
#Entrenamiento
red_xor.fit(X,y)

MLPClassifier(activation='logistic', hidden_layer_sizes=(2, 2, 1), max_iter=50,
              solver='lbfgs')

In [60]:
#predicciones para XOR
y_pred = red_xor.predict(X)
y_pred

array([0, 1, 1, 0])

In [63]:
precision = metric.accuracy_score(np.array(y).flatten(), np.array(y_pred).flatten(), normalize= True)
print(f"Precisión = {precision}")
print([inter.shape for inter in red_xor.intercepts_])
print([coef.shape for coef in red_xor.coefs_])

Precisión = 1.0
[(2,), (2,), (1,), (1,)]
[(2, 2), (2, 2), (2, 1), (1, 1)]


In [70]:
#Nuevo Dataset
# XNOR
X = [[0,0], [0,1], [1,0], [1,1]]
y = [1, 0, 0, 1]

In [71]:
red_xnor = MLPClassifier(solver = 'lbfgs', hidden_layer_sizes = (2,1), activation = 'logistic', max_iter = 500)
red_xnor.fit(X,y)
y_pred = red_xnor.predict(X)
print(f"Predicciones: {y_pred}")
precision = metric.accuracy_score(np.array(y).flatten(), np.array(y_pred).flatten(), normalize= True)
print(f"Precisión = {precision}")
print([inter.shape for inter in red_xnor.intercepts_])
print([coef.shape for coef in red_xnor.coefs_])

Predicciones: [1 0 0 1]
Precisión = 1.0
[(2,), (1,), (1,)]
[(2, 2), (2, 1), (1, 1)]


# Desafio nueva arquitectura

In [73]:
nueva_arquitectura = MLPClassifier(
    solver = 'lbfgs', 
    hidden_layer_sizes = (5, 5, 3, 3, 2, 1), 
    activation = 'logistic', 
    max_iter = 1000)
nueva_arquitectura

MLPClassifier(activation='logistic', hidden_layer_sizes=(5, 5, 3, 3, 2, 1),
              max_iter=1000, solver='lbfgs')